// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqmhhehbgiyhedpwxhvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxbWhoZWhiZ2l5aGVkcHd4aHZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NTA0NTIsImV4cCI6MjA3MzUyNjQ1Mn0.3vy7cNNLcANnCwskUzx3xDA3tj4O_-yoofcYJHO9pXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});